version: '3.8'

services:
  database:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - /tmp/mongo:/data/db

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/chat_app/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/chat_app/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    depends_on:
      - backend
    restart: always
