version: '3.8'

services:
  auth_app_database:
    container_name: auth_app_database
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    expose:
      - '27018'
    volumes:
      - /var/lib/mongodb-auth:/data/db

  chat_app_database:
    container_name: chat_app_database
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - /var/lib/mongodb-chat:/data/db

  auth_app:
    container_name: auth_app
    build:
      context: .
      dockerfile: ./backend/auth_app/Dockerfile
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8000'
    depends_on:
      - auth_app_database

  chat_app:
    container_name: chat_app
    build:
      context: .
      dockerfile: ./backend/chat_app/Dockerfile
    volumes:
      - ./backend/chat_app/application:/backend/chat_app/application
    restart: always
    ports:
      - '8000:8000'
    expose:
      - '8000'
    depends_on:
      - chat_app_database

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./backend/chat_app/Dockerfile
    volumes:
      - ./backend/chat_app/application:/backend/chat_app/applicatiom
    depends_on:
      - chat_app
      - redis

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    depends_on:
      - auth_app
      - chat_app
    restart: always

networks:
  default:
  auth_app:
  chat_app:
